- [x] Explore project context
- [x] Ask clarifying questions
- [x] Propose 2-3 approaches
- [x] Present design
- [ ] Write design doc
- [ ] Spec self-review
- [ ] User reviews written spec
- [x] Transition to implementation
