# -*- coding: utf-8 -*-
MINE_DISH = {
 # 바르셀로나
 'Disfrutar': '테이스팅 코스 · 멀티스페리컬 올리브 · 판체타 마카로니',
 'Hisop': '€100 테이스팅 코스 · 제철 카탈루냐 요리 · 아라카르트 가능',
 'Bar Pimentel': '크로케타 · 앤초비 · 나눠 먹는 타파스',
 'Bar Colom': '해산물 파에야 · 타파스 모둠 · 상그리아',
 'Ciutat Comtal': '푸아그라 올린 소고기 타파스 · 감자 오믈렛 · 하몽',
 'La Flauta': '감자 오믈렛 · 새우 요리 · 제철 타파스',
 'Tapa Tapa': '먹물 파에야 · 파타타스 브라바스 · 타파스 모둠',
 '3 Focs': '숯불 스테이크 · 구운 야채 · 카탈루냐 그릴 요리',
 'Lomo Alto': '60~180일 숙성 소고기 · 츄레톤 · 숙성 등심',
 'Barceloneta': '농어구이 · 굴 · 해산물 쌀 요리',
 'Luigi Ristorante': '피자 · 파스타 · 테라스 자리',
 'Honest Greens': '샐러드 볼 · 로스트 치킨 · 채식·비건 메뉴',
 'LA PAPA': '시나몬롤 · 브런치 플레이트 · 스페셜티 커피',
 'Jon Cake': '바스크 치즈케이크 · 고르곤졸라 맛 · 피스타치오 맛',
 '99 cheesecake': '€0.99 치즈케이크 · 토핑 추가 · 테이크아웃',
 'Xurreria Laietana': '츄러스 6개 + 핫초코 €5 · 포라 · 테이크아웃',
 'DelaCrem': '젤라토 2가지 맛 €3.90 · 피스타치오 · 제철 과일 맛',
 "Lucciano's": '피스타치오 젤라토 · 바나나 스플릿 · 젤라토 팝',
 # 리스본
 'Pastéis de Belém': '에그타르트 (파스텔 드 벨렝) · 계피·슈가 파우더 · 커피',
 'Time Out Market': '셰프 스톨 모음 · 에그타르트 · 해산물 요리',
 'Uma Marisqueira': '해산물밥 (arroz de marisco) · 문어 샐러드 · 조개 요리',
 'Pinóquio': '마늘새우 · 조개 요리 · 해산물 모둠',
 'O Coradinho': '문어구이 €12 · 매일 바뀌는 오늘의 메뉴 · 포르투갈 가정식',
 'O Cartaxinho': '조개 돼지고기 (porco à alentejana) · 점심 정식 · 가정식',
 'Palácio Chiado': '문어 요리 · 궁전 건물 다이닝 · 칵테일',
 'Mano a Mano': '프로슈토 루꼴라 피자 · 나폴리식 피자 · 파스타',
 'Han Table Barbecue': '이베리코 8종 양념구이 · 삼겹살 · 한식 밑반찬',
 'K-BOB': '김치찌개 · 김밥 · 양념치킨',
 'Nicolau': '잉글리시 브렉퍼스트 · 아보카도 토스트 · 팬케이크',
 'Amélia': '프렌치토스트 · 브런치 플레이트 · 뒷마당 자리',
 'A Brasileira': '비카 (에스프레소) · 에그타르트 · 페소아 동상 앞 테라스',
 'Café da Garagem': '커피와 케이크 · 그라사 지구 전망 · 극장 안 숨은 자리',
 'Quiosque Ribeira das Naus': '포르투 토닉 · 강변 야외석 · 간단한 안주',
 'Park Rooftop': '칵테일 · 루프탑 전망 · 안주 플레이트',
 'A Padaria Portuguesa': '조식 세트 €3-5 (커피+생오렌지주스) · 크루아상 · 에그타르트',
 'Choupana Caffe': '크루아상 · 커피 · 조식',
 'Jeronymo': '커피 · 크루아상 · 기차 전 간단한 조식',
 'Geladaria Surf': '젤라토 · 늦은 밤 디저트',
 'Woori 한국마트': '수제 김치 · 한국 식료품 · 라면·과자',
 'KoPo Mart': '한국 식료품 · 냉동식품 · 라면',
 'Galveias 궁전 도서관': '뒷마당 카페 · 열람실 · 궁전 건물',
 'Biblioteca do INA': '열람실 · 조용한 작업 공간',
 'Spacio Shopping': '푸드코트 · 쇼핑 · 무료 주차 2시간',
 # 포르투
 'Tapabento S.Bento': '대구 크로켓 · 돼지목살 타코 · 타파스 모둠',
 'Espaço Porto Cruz': '포트와인 테이스팅 · 루프탑 노을 전망 · 안주 플레이트',
}
